ETransferProject/etransfer-web

src/pageComponents/DepositContent/DepositInfo/index.tsx
src/pageComponents/WithdrawContent/ContractAddress/styles.module.scss
src/pageComponents/WithdrawContent/DoubleCheckModal/index.tsx
src/pageComponents/WithdrawContent/SuccessModal/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/pageComponents/WithdrawContent/styles.module.scss
src/utils/calculate.ts

1 Modify the amount and refresh withdraw info
2 $ display rule changes
3 Mobile terminal remaining-limit displays line breaks

feat: Modify the amount and refresh withdraw info

---

src/components/CommonDrawer/index.tsx
src/components/CommonModal/index.tsx
src/components/Header/SelectMenu/index.tsx
src/components/Header/SelectMenu/styles.module.scss
src/components/SelectChain/index.tsx
src/pageComponents/Content/index.tsx
src/pageComponents/DepositContent/index.tsx
src/pageComponents/HistoryContent/AddressBox/index.tsx
src/pageComponents/HistoryContent/MobileHistoryContent/HistoryCardItem/index.tsx
src/pageComponents/HistoryContent/WebHistoryContent/WebHistoryTable/index.tsx
src/pageComponents/HistoryContent/index.tsx
src/pageComponents/SelectWallet/MobileSelectWallet/index.tsx
src/pageComponents/SelectWallet/MobileSelectWallet/styles.module.scss
src/pageComponents/WithdrawContent/RemainingQuota/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/pageComponents/WithdrawContent/styles.module.scss
src/store/reducers/common/slice.ts
src/store/reducers/userAction/slice.ts
src/utils/aelfUtils.tsx
src/utils/common.ts
src/wallet/portkeyWalletV1.ts

resolve: #148 
1. Support USDT transfer in aelf homogeneous chain.
2. Optimize interaction：
- Add loading during the account balance loading process
- The account balance is loaded, and the withdrawal is verified.
- Optimize mobile UI.

Support USDT transfer in aelf homogeneous chain.

---

src/pageComponents/DepositContent/DepositInfo/index.tsx
src/pageComponents/HistoryContent/FeeInfo/index.tsx
src/pageComponents/HistoryContent/TokenBox/index.tsx
src/pageComponents/SelectNetwork/NetworkCard/index.tsx
src/pageComponents/SelectToken/TokenCard/index.tsx
src/pageComponents/SelectToken/index.tsx
src/pageComponents/WithdrawContent/DoubleCheckModal/index.tsx
src/pageComponents/WithdrawContent/RemainingQuota/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/utils/format.ts

Replace SGR-1 to SGR

---

src/pageComponents/DepositContent/index.tsx
src/pageComponents/Home/Content/index.tsx
src/types/index.ts

The deposit page supports routing parameter configuration.

---

src/pageComponents/DepositContent/SelectToken/index.tsx
src/store/reducers/token/slice.ts

Fixed the token cannot be switched occasionally on the deposit page.

---

src/components/FormTextarea/index.tsx
src/pageComponents/DepositContent/Calculator/index.tsx
src/pageComponents/DepositContent/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/types/index.ts

1. Add routing to the deposit page to pass network. close #169 
2. Optimize withdrawal address input. close #170

Add routing to the deposit and optimize withdrawal address.

---

src/pageComponents/DepositContent/Calculator/index.tsx
src/pageComponents/DepositContent/ExchangeRate/index.tsx
src/pageComponents/DepositContent/MobileDepositContent/index.tsx
src/pageComponents/DepositContent/SelectChainWrapper/index.tsx
src/pageComponents/DepositContent/WebDepositContent/index.tsx

Support ELF Swap

---

next.config.js
src/api/list.ts
src/api/utils.ts
src/app/recaptcha/page.tsx
src/app/recaptcha/styles.module.scss
src/components/GoogleRecaptcha/index.tsx
src/components/GoogleRecaptcha/types.ts
src/components/Header/LoginAndProfile/ConnectWalletButton/index.tsx
src/constants/calculate.ts
src/constants/misc.ts
src/hooks/authToken.ts
src/pageComponents/DepositContent/Calculator/index.tsx
src/pageComponents/DepositContent/ExchangeRate/index.tsx
src/pageComponents/DepositContent/index.tsx
src/pageComponents/WithdrawContent/SuccessModal/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/portkeySDK/utils/authToken.ts
src/portkeySDK/utils/contract.ts
src/provider/index.tsx
src/provider/webLoginProvider.tsx
src/store/Provider/store.ts
src/styles/components.scss
src/styles/global.scss
src/types/api.ts
src/utils/api/user.ts
src/utils/calculate.ts
src/utils/contract.tsx
src/utils/modal/googleReCaptchaModal.tsx
src/utils/myEvent.ts

1. Support connect NightElf. close #184 
2. Fix withdrawal information display. close #187 
3. Fixed the chain list issue when switching to token. close #189

Support connect NightElf.

---

src/pageComponents/DepositContent/index.tsx
src/pageComponents/WithdrawContent/SelectChainWrapper/index.tsx

Fix the interaction of the deposit page.

---

.github/workflows/sonarqube.yaml

Add SonarQube configuration to analyze code and check code quality and security. close #213

Config SonarQube git action

---

src/constants/index.ts
src/constants/platform/AELF.ts
src/constants/platform/tDVV.ts
src/hooks/common.ts
src/pageComponents/DepositContent/index.tsx
src/pageComponents/HistoryContent/AmountBox/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/utils/calculate.ts

1. Added new token ACORNS for deposit. close #217 
2. Modify the url of the contract method call. close #218 
3. Fix: offline networks cannot be selected. #219

Add new deposit token and fix network display logic.

---

src/pageComponents/InfoPage/Overview/components/BarChartHeader/index.tsx
src/pageComponents/InfoPage/TokenDashboard/ColumnComponents/Networks/styles.module.scss

Fix networks tooltip style of token dashboard. close #223

Fix networks tooltip style of token dashboard.

---

.github/workflows/mainnet-package.yaml
src/pageComponents/DepositContent/Calculator/index.tsx
src/pageComponents/DepositContent/ExchangeRate/index.tsx
src/pageComponents/DepositContent/index.tsx
src/pageComponents/WithdrawContent/index.tsx
src/utils/api/error.ts

Using a new service deployment. close #225

Using a new service deployment.

---

src/pageComponents/HistoryContent/AmountBox/index.tsx

Delete the logic of formatting history amount data at front-end. #243

Delete the logic of formatting history amount data at front-end.

---

src/constants/footer.ts
src/pageComponents/WithdrawContent/WithdrawFooter/index.tsx

Update aelfscan text. closed #264

Update aelfscan text.

---

src/pageComponents/CrossChainTransferPage/index.tsx

Update Error Message for Maximum Transaction Amount Validation. closed #275

Update Error Message for Maximum Transaction Amount Validation.

---

src/components/CommonTip/index.tsx
src/components/CommonTip/styles.module.scss
src/components/Header/LoginAndProfile/ConnectWalletModal/EVMList/index.tsx
src/components/Header/LoginAndProfile/ConnectWalletModal/aelfList/Address/index.tsx
src/components/Modal/SynchronizingChainModal/index.tsx
src/components/NetworkSelectModal/index.tsx
src/components/TokenSelectModal/index.tsx
src/components/TokenSelectModal/styles.module.scss
src/constants/deposit.ts
src/constants/listing.tsx
src/constants/misc.ts
src/pageComponents/DepositContent/DepositInfo/index.tsx
src/pageComponents/DepositContent/MobileDepositContent/index.tsx
src/pageComponents/DepositContent/WebDepositContent/index.tsx
src/pageComponents/HistoryContent/FeeInfo/index.tsx
src/pageComponents/HistoryContent/MobileHistoryContent/HistoryCardItem/index.tsx
src/pageComponents/HistoryContent/WebHistoryContent/WebHistoryTable/index.tsx
src/pageComponents/InfoPage/TransferDetail/TransferDetailBody/index.tsx
src/pageComponents/InfoPage/TransferDetail/components/TokenAmount/index.tsx
src/pageComponents/ListingContent/InitializeLiquidityPool/index.tsx
src/pageComponents/ListingContent/SelectChain/CreationProgressModal/index.tsx
src/pageComponents/ListingContent/SelectChain/index.tsx
src/pageComponents/ListingContent/TokenInformation/TokenSelect/index.tsx
src/pageComponents/ListingContent/TokenInformation/index.tsx
src/pageComponents/TransferDetail/TransferDetailMain/index.tsx
src/pageComponents/TransferDetail/TransferDetailMain/styles.module.scss
src/types/api.ts
src/utils/notice.tsx

Add service fee logic to the deposit function. close #279

Add service fee logic to the deposit function.

---

src/components/TokenSelectModal/index.tsx
src/constants/footer.ts

Hidden listing application entrance. closed #281

Hidden listing application entrance.

---

src/components/CommonTip/index.tsx
src/components/CommonTooltipSwitchModal/index.tsx
src/constants/deposit.ts
src/pageComponents/DepositContent/DepositInfo/index.tsx
src/pageComponents/DepositContent/MobileDepositContent/index.tsx
src/pageComponents/DepositContent/WebDepositContent/index.tsx
src/types/api.ts

Update service fee logic. close #283

Update service fee logic.

---

src/constants/wallet/EVM.ts
src/provider/wallet/EVM.tsx

Modify ethereum mainnet RPC node. closed #285

 Modify ethereum mainnet RPC node.

---

README.md

Modify unit tests coverage precision. #289

Modify unit tests coverage precision.

---

.github/workflows/codecov.yml

Modify ut coverage name and config. #289

Modify ut coverage name and config.

---

.github/workflows/mainnet-package.yaml
.github/workflows/prerelease-package.yaml
.github/workflows/testnet-package.yaml
src/pageComponents/CrossChainTransferPage/CrossChainTransferForm/index.tsx
src/pageComponents/CrossChainTransferPage/index.tsx
src/pageComponents/CrossChainTransferPage/utils.ts
src/pageComponents/Withdraw/utils.ts
src/types/api.ts

Optimize the Network Deactivation Function to Allow Individual Token Network Deactivation in Transfer Operations. close #298

Optimize the Network Deactivation Function to Allow Individual Token Network Deactivation in Transfer Operations
